### ISSUE TITLE
Final Prototype - Andrew Tasks

### ISSUE THREAD

**Issue by CarylHenry** [carylsquad/minimism#23]
Make custom fields more indicative (click out of the field, + symbol)
       -Might be nice to add more than one custom field
For the final question, change the next arrow to a to “submit” button
       -Makes it more obvious that user is done

**Comment by atfinke** [comment]
@CarylHenry what does 'Make custom fields more indicative (click out of the field, + symbol)' mean?Highlighting? What fields? What is the + symbol?

**Comment by CarylHenry** [comment]
You can click on the "other" buttons to turn them into text fields. Then once you hit "enter" those text fields turn back into buttons with an updated label. It's the idea of making the "enter" part where it goes back into being a button more obvious to the user. Also recommended that if you click elsewhere on the screen the text field turns back into a button but that felt more optional.
